from django.urls import path
from . import views

urlpatterns = [
    path('parcours/', views.allParcours),
    path('parcours/<id>/', views.getParcour),
    path('parcours/add', views.addParcour),
    path('parcours/<id>/update', views.updateParcour),
    path('parcours/<id>/delete', views.deleteParcour),
    path('comptes/', views.allCompte),
    path('comptes/users/', views.allUserCompte),
    path('comptes/<id>/', views.getOneCompte),
    path('auth/<username>/password/<password>/', views.authentification),
    path('parcours/<id_parcours>/comptes/add', views.addCompte),
    path('comptes/<id>/update', views.updateCompte),
    path('comptes/<id>/change_pw', views.changePasswordCompte),
    path('comptes/<id>/delete', views.deleteCompte),
    path('sessions/', views.allSession),
    path('sessions/<id>/', views.getSession),
    path('sessions/<id>/close', views.closeSession),
    path('sessions/add', views.addSession),
    path('sessions/<id>/update', views.updateSession),
    path('sessions/<id>/delete', views.deleteSession),
    path('matieres/', views.allMatieres),
    path('parcours/<id_parcours>/matieres/', views.allMatieresParcour),
    path('matieres/<id>/', views.getOneMatiere),
    path('parcours/<id_parcours>/matieres/add', views.addMatiere),
    path('matieres/<id>/update', views.updateMatiere),
    path('matieres/<id>/delete', views.deleteMatiere),
    path('parcours/<id_parcours>/sessions/<id_session>/dossiers/', views.allDossiersParcour),
    path('dossiers/<id>/', views.getOneDossier),
    path('sessions/<id_session>/dossiers/', views.allDossiersAllParcours),
    path('parcours/<id_parcours>/sessions/<id_session>/dossiers/add', views.addDossier),
    path('dossiers/<id>/update', views.updateDossier),
    path('dossiers/<id>/delete', views.deleteDossier),
    path('dossiers/<id_dossier>/releves', views.getRNDossier),
    path('dossiers/<id_dossier>/releves/add', views.addRNToDossier),
    path('dossiers/<id_dossier>/releves/update', views.updateRNOfDossier),
    path('releves/<id_rn>/notes', views.getAllNotesOfRN),
    path('releves/<id_rn>/matieres/<id_matiere>/notes', views.getOneNote),
    path('releves/<id_rn>/matieres/<id_matiere>/notes/add', views.addNote),
    path('notes/<id>/update', views.updateNote)
]
