# Generated by Django 2.2.18 on 2021-09-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parcours',
            field=models.CharField(default='NOT-DEFINED', max_length=255),
            preserve_default=False,
        ),
    ]
