# Generated by Django 2.2.18 on 2021-09-11 09:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0004_compte_parcours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sessionId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sessionDescription', models.CharField(max_length=255)),
                ('sessionStatus', models.CharField(max_length=10)),
                ('sessionAnnee', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('matiereCode', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('matiereName', models.CharField(max_length=20)),
                ('matiereCoeff', models.IntegerField()),
                ('matiereIdParcours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selection.Parcours')),
            ],
        ),
    ]
