# Generated by Django 2.2.18 on 2021-09-11 10:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0005_matiere_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='matiereId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='matiereCode',
            field=models.CharField(max_length=8),
        ),
    ]
