# Generated by Django 2.2.18 on 2021-09-11 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0006_auto_20210911_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compte',
            old_name='compteIdParcours',
            new_name='compteParcours',
        ),
        migrations.RenameField(
            model_name='matiere',
            old_name='matiereIdParcours',
            new_name='matiereParcours',
        ),
    ]
