# Generated by Django 2.2.18 on 2021-09-11 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0007_auto_20210911_1030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
