# Generated by Django 2.2.18 on 2021-09-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0008_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='compteUsername',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='sessionAnnee',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='sessionStatus',
            field=models.CharField(choices=[('F', 'FERMEE'), ('O', 'OUVERTE')], max_length=10),
        ),
    ]
