# Generated by Django 2.2.18 on 2021-09-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0009_auto_20210916_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='sessionAnnee',
            field=models.CharField(max_length=9),
        ),
    ]
