# Generated by Django 2.2.18 on 2021-09-16 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0013_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
