# Generated by Django 2.2.18 on 2021-09-16 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0015_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='noteMatiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='selection.Matiere'),
        ),
    ]
