# Generated by Django 2.2.18 on 2021-09-16 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0016_auto_20210916_2004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
