# Generated by Django 2.2.18 on 2021-09-16 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0021_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='ReleveNote',
        ),
    ]
