# Generated by Django 2.2.18 on 2021-09-16 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0023_auto_20210916_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relevenote',
            name='releveNoteMatiere',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='ReleveNote',
        ),
    ]
