# Generated by Django 2.2.18 on 2021-09-19 19:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0026_auto_20210916_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relevenote',
            name='releveNoteId',
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('dossierId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dossierNumInscription', models.CharField(editable=False, max_length=8)),
                ('dossierName', models.CharField(max_length=50)),
                ('dossierDateNaissance', models.DateField()),
                ('dossierLieuNaissance', models.CharField(max_length=50)),
                ('dossierParcours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selection.Parcours')),
                ('dossierSession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selection.Session')),
            ],
        ),
        migrations.AddField(
            model_name='relevenote',
            name='releveNote',
            field=models.OneToOneField(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='selection.Dossier'),
        ),
    ]
