# Generated by Django 2.2.18 on 2021-09-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0027_auto_20210919_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='compteUserRole',
            field=models.CharField(choices=[('ADMIN', 'ADMINISTRATEUR'), ('USER', 'UTILISATEUR')], default='USER', max_length=5),
        ),
    ]
