# Generated by Django 2.2.18 on 2021-09-25 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0028_compte_compteuserrole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compte',
            old_name='compteUserRole',
            new_name='compteRole',
        ),
    ]
