# Generated by Django 2.2.18 on 2021-10-10 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0036_auto_20211010_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relevenote',
            old_name='releveNoteSession',
            new_name='releveNoteAnnee',
        ),
    ]
