# Generated by Django 2.2.18 on 2021-10-10 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0039_auto_20211010_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='matiereParcour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='selection.Parcours'),
        ),
    ]
