# Generated by Django 2.2.18 on 2021-10-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0040_matiere_matiereparcour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='matiereName',
            field=models.CharField(max_length=50),
        ),
    ]
